{
 "title": "yt-backup overview",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Videos monitored",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM videos" }
   ]
  },
  {
   "title": "Videos in Archive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM `videos` WHERE downloaded IS NOT NULL"
    }
   ]
  },
  {
   "title": "Videos only in archive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as videos FROM videos WHERE online = 0 OR online = 3;"
    }
   ]
  },
  {
   "title": "Videos in Download Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM `videos` WHERE downloaded IS NULL AND download_required = 1 AND copyright IS NULL AND videos.online = 1"
    }
   ]
  },
  {
   "title": "Time used downloading",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(duration) FROM `operations` WHERE `operation_type` = 'download_videos'"
    }
   ]
  },
  {
   "title": "Time used uploading",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(duration) FROM `operations` WHERE `operation_type` = 'rclone_upload'"
    }
   ]
  },
  {
   "title": "Time used fetching metadata",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT SUM(duration) FROM `operations` WHERE `operation_type` = 'get_video_infos' OR `operation_type` = 'get_playlists'"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT statistic_value FROM statistics WHERE statistic_type = 'status' LIMIT 1"
    }
   ]
  },
  {
   "title": "Channel stats",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT * FROM `downloaded_and_available_videos_by_channel_with_percent`"
    }
   ]
  },
  {
   "title": "Videos downloaded per day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT download_date AS time, number FROM `videos_downloaded_at_date` WHERE download_date > \"2010-01-01 00:00:00\""
    }
   ]
  },
  {
   "title": "Video resolutions",
   "type": "table",
   "gridPos": { "h": 13, "w": 3, "x": 18, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as videos,resolution FROM `videos` WHERE resolution IS NOT NULL GROUP BY resolution"
    }
   ]
  },
  {
   "title": "Videos copyrighted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as video_count FROM videos WHERE downloaded IS NULL AND download_required = 1 AND copyright IS NOT NULL"
    }
   ]
  },
  {
   "title": "Downloaded last 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT SUM(size) FROM videos WHERE downloaded >= now() - INTERVAL 1 DAY;"
    }
   ]
  },
  {
   "title": "Archive Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "decbytes", "label": "archive size" }
   ],
   "targets": [
    {
     "rawSql": "SELECT statistic_date AS time, CAST(statistic_value AS SIGNED) AS archive_size FROM statistics WHERE statistic_type = 'archive_size';"
    }
   ]
  },
  {
   "title": "Unlisted videos in archive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as videos FROM videos WHERE online = 4;"
    }
   ]
  },
  {
   "title": "Lost videos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as videos FROM videos WHERE videos.downloaded IS NULL AND (videos.online = 0 OR videos.online = 3)"
    }
   ]
  },
  {
   "title": "Currently Downloading",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT statistic_value FROM statistics WHERE statistic_type = 'currently_downloading' LIMIT 1"
    }
   ]
  }
 ]
}